@extends('layouts.app')
@section('title', $shipment->shipment_number.' · SellAssist KH')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a href="{{ route('delivery.shipments.index') }}">← Delivery</a><h1 class="h3 mt-2 mb-1">{{ $shipment->shipment_number }}</h1><div class="text-secondary">{{ $shipment->provider->name }} · {{ $shipment->tracking_number ?: 'Tracking not assigned' }}</div></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" target="_blank" href="{{ route('delivery.shipments.label', $shipment) }}">Print label</a><span class="badge text-bg-secondary fs-6 align-self-center">{{ $shipment->status->label() }}</span></div></div>
<div class="row g-4"><div class="col-lg-8">
<div class="card mb-4"><div class="card-header bg-white"><strong>Shipment details</strong></div><div class="card-body"><div class="row g-3"><div class="col-md-6"><div class="small text-secondary">Order</div><a href="{{ route('orders.show', $shipment->order) }}">{{ $shipment->order->order_number }}</a></div><div class="col-md-6"><div class="small text-secondary">Created by</div>{{ $shipment->creator?->name ?: 'System' }}</div><div class="col-md-6"><div class="small text-secondary">Recipient</div>{{ $shipment->recipient_name }}<br>{{ $shipment->recipient_phone ?: 'No phone' }}</div><div class="col-md-6"><div class="small text-secondary">Delivery address</div>{{ $shipment->delivery_address ?: 'No address' }}</div>@if($shipment->notes)<div class="col-12"><div class="small text-secondary">Notes</div>{{ $shipment->notes }}</div>@endif</div></div></div>
<div class="card"><div class="card-header bg-white"><strong>Status history</strong></div><div class="list-group list-group-flush">@foreach($shipment->histories as $history)<div class="list-group-item"><div class="d-flex justify-content-between gap-3"><span class="fw-semibold">{{ $history->status->label() }}</span><small class="text-secondary">{{ $history->occurred_at->format('d M Y H:i') }}</small></div>@if($history->notes)<div>{{ $history->notes }}</div>@endif<small class="text-secondary">{{ $history->creator?->name ?: 'System' }}</small></div>@endforeach</div></div>
</div><div class="col-lg-4">
@if($shipment->provider->integration_enabled)<div class="card mb-4"><div class="card-body"><h2 class="h5">Provider integration</h2><dl class="row mb-3"><dt class="col-6">Adapter</dt><dd class="col-6 text-end">{{ $shipment->provider->adapter->label() }}</dd><dt class="col-6">Sync status</dt><dd class="col-6 text-end">{{ $shipment->integration_status->label() }}</dd><dt class="col-6">External ID</dt><dd class="col-6 text-end">{{ $shipment->external_id ?: '—' }}</dd><dt class="col-6">Last sync</dt><dd class="col-6 text-end">{{ $shipment->last_synced_at?->format('d M H:i') ?: 'Never' }}</dd></dl>@if($shipment->integration_error)<div class="alert alert-danger small">{{ $shipment->integration_error }}</div>@endif @can('delivery.update')@if(!$shipment->external_id)<form method="POST" action="{{ route('delivery.shipments.integration.submit', $shipment) }}">@csrf<button class="btn btn-primary w-100" @disabled($shipment->order->status->value !== 'packed')>Submit to provider</button>@if($shipment->order->status->value !== 'packed')<div class="form-text">Pack the order before submission.</div>@endif</form>@else<form method="POST" action="{{ route('delivery.shipments.integration.sync', $shipment) }}">@csrf<button class="btn btn-outline-primary w-100">Sync provider status</button></form>@endif @endcan</div>@if($shipment->integrationLogs->isNotEmpty())<div class="list-group list-group-flush">@foreach($shipment->integrationLogs->take(5) as $log)<div class="list-group-item"><div class="d-flex justify-content-between"><span>{{ ucfirst($log->operation) }}</span><span class="badge {{ $log->status === 'succeeded' ? 'text-bg-success' : 'text-bg-danger' }}">{{ ucfirst($log->status) }}</span></div><small class="text-secondary">{{ $log->created_at->format('d M H:i') }}</small></div>@endforeach</div>@endif</div>@endif
@can('delivery.update') @if($nextStatuses !== [])<div class="card mb-4"><div class="card-body"><h2 class="h5">Update delivery</h2><form method="POST" action="{{ route('delivery.shipments.status.update', $shipment) }}">@csrf @method('PATCH')<div class="mb-3"><label class="form-label">Next status *</label><select class="form-select" name="status" required>@foreach($nextStatuses as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Tracking number</label><input class="form-control" name="tracking_number" value="{{ old('tracking_number', $shipment->tracking_number) }}"></div><div class="mb-3"><label class="form-label">Update notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><button class="btn btn-primary w-100">Update status</button></form></div></div>@endif @endcan
<div class="card mb-4"><div class="card-body"><h2 class="h5">COD reconciliation</h2><dl class="row mb-0"><dt class="col-6">Expected</dt><dd class="col-6 text-end">{{ $shipment->currency->value }} {{ number_format((float) $shipment->cod_amount, 2) }}</dd><dt class="col-6">Remitted</dt><dd class="col-6 text-end">{{ number_format($remittedTotal, 2) }}</dd><dt class="col-6">Balance</dt><dd class="col-6 text-end fw-bold">{{ number_format($codBalance, 2) }}</dd><dt class="col-6">Status</dt><dd class="col-6 text-end">{{ $shipment->cod_status->label() }}</dd></dl></div>@if($shipment->remittances->isNotEmpty())<div class="list-group list-group-flush">@foreach($shipment->remittances as $remittance)<div class="list-group-item"><div class="d-flex justify-content-between"><span>{{ $remittance->reference ?: 'No reference' }}</span><strong>{{ number_format((float) $remittance->amount, 2) }}</strong></div><small class="text-secondary">{{ $remittance->remitted_at->format('d M Y H:i') }} · {{ $remittance->creator?->name ?: 'System' }}</small></div>@endforeach</div>@endif</div>
@can('delivery.cod.reconcile') @if($shipment->status->value === 'delivered' && $codBalance > 0)<div class="card"><div class="card-body"><h2 class="h5">Record remittance</h2><form method="POST" action="{{ route('delivery.shipments.cod-remittances.store', $shipment) }}">@csrf<div class="mb-3"><label class="form-label">Amount *</label><div class="input-group"><span class="input-group-text">{{ $shipment->currency->value }}</span><input class="form-control" type="number" step="0.01" min="0.01" max="{{ number_format($codBalance, 2, '.', '') }}" name="amount" required></div></div><div class="mb-3"><label class="form-label">Provider reference</label><input class="form-control" name="reference"></div><div class="mb-3"><label class="form-label">Received at</label><input class="form-control" type="datetime-local" name="remitted_at" value="{{ now()->format('Y-m-d\TH:i') }}"></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><button class="btn btn-primary w-100">Record COD remittance</button></form></div></div>@endif @endcan
</div></div>
@endsection
