@extends('layouts.app')
@section('title', $product->name.' · SellAssist KH')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><a href="{{ route('products.index') }}">← Products</a><h1 class="h3 mt-2 mb-0">{{ $product->name }}</h1><span class="text-secondary">{{ $product->sku ?: 'No SKU' }} · ${{ number_format((float) $product->base_price, 2) }}</span></div>@can('products.update')<a class="btn btn-outline-secondary" href="{{ route('products.edit', $product) }}">Edit product</a>@endcan</div>
<div class="row g-4">
    <div class="col-lg-8"><div class="card"><div class="card-header bg-white"><strong>Variants</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Variant</th><th>SKU</th><th>Price</th><th>Cost</th><th>Stock</th><th>Status</th></tr></thead><tbody>@forelse($product->variants as $variant)<tr><td>{{ $variant->display_name }}</td><td>{{ $variant->sku ?: '—' }}</td><td>{{ $variant->price === null ? 'Base price' : '$'.number_format((float) $variant->price, 2) }}</td><td>{{ $variant->cost === null ? '—' : '$'.number_format((float) $variant->cost, 2) }}</td><td>{{ $variant->stock_quantity }} <small class="text-secondary">(low at {{ $variant->low_stock_threshold }})</small></td><td>{{ $variant->active ? 'Active' : 'Inactive' }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No variants. Base stock: <strong>{{ $product->stock_quantity }}</strong>.</td></tr>@endforelse</tbody></table></div></div></div>
    @can('products.create')<div class="col-lg-4"><div class="card"><div class="card-body"><h2 class="h5">Add variant</h2><form method="POST" action="{{ route('products.variants.store', $product) }}">@csrf
        <div class="row g-2"><div class="col-6"><label class="form-label">Color</label><input class="form-control" name="color" value="{{ old('color') }}"></div><div class="col-6"><label class="form-label">Size</label><input class="form-control" name="size" value="{{ old('size') }}"></div><div class="col-12"><label class="form-label">SKU</label><input class="form-control" name="sku" value="{{ old('sku') }}"></div><div class="col-6"><label class="form-label">Price override</label><input class="form-control" type="number" step="0.01" min="0" name="price" value="{{ old('price') }}"></div><div class="col-6"><label class="form-label">Cost</label><input class="form-control" type="number" step="0.01" min="0" name="cost" value="{{ old('cost') }}"></div><div class="col-6"><label class="form-label">Initial stock</label><input class="form-control" type="number" min="0" name="initial_stock" value="{{ old('initial_stock', 0) }}"></div><div class="col-6"><label class="form-label">Low at</label><input class="form-control" type="number" min="0" name="low_stock_threshold" value="{{ old('low_stock_threshold', 5) }}" required></div><input type="hidden" name="active" value="1"></div><button class="btn btn-primary w-100 mt-3">Add variant</button>
    </form></div></div></div>@endcan
</div>
@endsection

