<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $order->order_number }} · Receipt</title>
<style>body{font-family:Arial,"Noto Sans Khmer",sans-serif;color:#111;max-width:760px;margin:2rem auto;padding:0 1rem}header{display:flex;justify-content:space-between;gap:1rem;border-bottom:2px solid #111;padding-bottom:1rem}table{width:100%;border-collapse:collapse;margin-top:1.5rem}th,td{padding:.6rem;border-bottom:1px solid #ddd;text-align:left}.number{text-align:right}.totals{margin:1.5rem 0 0 auto;max-width:340px}.totals div{display:flex;justify-content:space-between;padding:.3rem}.grand{font-size:1.2rem;font-weight:bold;border-top:2px solid #111;margin-top:.4rem;padding-top:.7rem!important}.no-print{margin-bottom:1rem}@media print{.no-print{display:none}body{margin:0;max-width:none}}</style></head><body>
<button class="no-print" onclick="window.print()">Print / បោះពុម្ព</button>
<header><div><h1>SellAssist KH</h1><div>Receipt / បង្កាន់ដៃ</div></div><div><strong>{{ $order->order_number }}</strong><br>{{ $order->created_at->format('d M Y H:i') }}</div></header>
<section><p><strong>Customer / អតិថិជន:</strong> {{ $order->customer_name ?: '—' }}<br><strong>Phone / ទូរស័ព្ទ:</strong> {{ $order->customer_phone ?: '—' }}<br><strong>Address / អាសយដ្ឋាន:</strong> {{ $order->shipping_address ?: '—' }}</p></section>
<table><thead><tr><th>Product / ផលិតផល</th><th class="number">Qty / បរិមាណ</th><th class="number">Price / តម្លៃ</th><th class="number">Total / សរុប</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }} @if($item->variant_name)<small>({{ $item->variant_name }})</small>@endif</td><td class="number">{{ $item->quantity }}</td><td class="number">{{ number_format((float) $item->unit_price, 2) }}</td><td class="number">{{ number_format((float) $item->line_total, 2) }}</td></tr>@endforeach</tbody></table>
<div class="totals"><div><span>Subtotal</span><span>{{ $order->currency->value }} {{ number_format((float) $order->subtotal, 2) }}</span></div><div><span>Discount</span><span>- {{ number_format((float) $order->discount, 2) }}</span></div><div><span>Delivery</span><span>+ {{ number_format((float) $order->delivery_fee, 2) }}</span></div><div class="grand"><span>Total / សរុប</span><span>{{ $order->currency->value }} {{ number_format((float) $order->total, 2) }}</span></div></div>
<p style="margin-top:3rem;text-align:center">Thank you / អរគុណ</p>
</body></html>
