@extends('layouts.app')
@section('title', $order->order_number.' · SellAssist KH')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><a href="{{ route('orders.index') }}">← Orders</a><h1 class="h3 mt-2 mb-1">{{ $order->order_number }}</h1><div class="text-secondary">Created {{ $order->created_at->format('d M Y, H:i') }} by {{ $order->creator?->name ?: 'System' }}</div></div>
    <div class="d-flex align-items-center gap-2">
        <a class="btn btn-sm btn-outline-secondary" href="{{ route('orders.receipt', $order) }}" target="_blank">Receipt / បង្កាន់ដៃ</a>
        @can('orders.update') @if(in_array($order->status->value, ['draft', 'new'], true))<a class="btn btn-sm btn-outline-primary" href="{{ route('orders.edit', $order) }}">Amend order</a>@endif @endcan
        <span class="badge text-bg-secondary fs-6">{{ $order->status->label() }}</span><span class="badge text-bg-info fs-6">{{ $order->payment_status->label() }}</span>
    </div>
</div>

@if($nextStatuses !== [])<div class="card mb-4"><div class="card-body d-flex flex-wrap align-items-center gap-2"><strong class="me-2">Next action</strong>@foreach($nextStatuses as $status)@php($permission = $status->value === 'cancelled' ? 'orders.cancel' : 'orders.update') @can($permission)<form method="POST" action="{{ route('orders.status.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status->value }}"><button class="btn btn-sm {{ $status->value === 'cancelled' ? 'btn-outline-danger' : 'btn-primary' }}">{{ $status->label() }}</button></form>@endcan @endforeach</div></div>@endif

<div class="row g-4">
    <div class="col-xl-8">
        <div class="card mb-4"><div class="card-header bg-white"><strong>Items</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Product snapshot</th><th>SKU</th><th class="text-end">Price</th><th class="text-end">Qty</th><th class="text-end">Returned</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }}<div class="small text-secondary">{{ $item->variant_name }}</div></td><td>{{ $item->sku ?: '—' }}</td><td class="text-end">{{ number_format((float) $item->unit_price, 2) }}</td><td class="text-end">{{ $item->quantity }}</td><td class="text-end">{{ $item->returnItems->sum('quantity') }}</td><td class="text-end fw-semibold">{{ number_format((float) $item->line_total, 2) }}</td></tr>@endforeach</tbody></table></div>
            <div class="card-body border-top"><div class="row justify-content-end"><div class="col-sm-6 col-lg-5"><div class="d-flex justify-content-between"><span>Subtotal</span><span>{{ $order->currency->value }} {{ number_format((float) $order->subtotal, 2) }}</span></div><div class="d-flex justify-content-between"><span>Discount</span><span>− {{ number_format((float) $order->discount, 2) }}</span></div><div class="d-flex justify-content-between"><span>Delivery</span><span>+ {{ number_format((float) $order->delivery_fee, 2) }}</span></div><div class="d-flex justify-content-between border-top mt-2 pt-2 fs-5 fw-bold"><span>Total</span><span>{{ $order->currency->value }} {{ number_format((float) $order->total, 2) }}</span></div></div></div></div>
        </div>

        @can('payments.view')
        <div class="card mb-4"><div class="card-header bg-white"><strong>Payments</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Recorded by</th><th class="text-end">Paid</th><th class="text-end">Refunded</th></tr></thead><tbody>@forelse($order->payments as $payment)<tr><td>{{ $payment->paid_at->format('d M Y H:i') }}</td><td>{{ $payment->payment_method->label() }}</td><td>{{ $payment->reference ?: '—' }}</td><td>{{ $payment->creator?->name ?: 'System' }}</td><td class="text-end">{{ $payment->currency->value }} {{ number_format((float) $payment->amount, 2) }}</td><td class="text-end">{{ number_format((float) $payment->refunds->sum('amount'), 2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-4">No payments recorded.</td></tr>@endforelse</tbody></table></div></div>

        @if($order->refunds->isNotEmpty())<div class="card mb-4"><div class="card-header bg-white"><strong>Refund ledger</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Method</th><th>Return</th><th>Reference</th><th>By</th><th class="text-end">Amount</th></tr></thead><tbody>@foreach($order->refunds as $refund)<tr><td>{{ $refund->refunded_at->format('d M Y H:i') }}</td><td>{{ $refund->refund_method->label() }}</td><td>{{ $refund->orderReturn?->return_number ?: 'Standalone' }}</td><td>{{ $refund->reference ?: '—' }}</td><td>{{ $refund->creator?->name ?: 'System' }}</td><td class="text-end text-danger">− {{ $refund->currency->value }} {{ number_format((float) $refund->amount, 2) }}</td></tr>@endforeach</tbody></table></div></div>@endif
        @endcan

        @can('returns.view') @if($order->returns->isNotEmpty())<div class="card mb-4"><div class="card-header bg-white"><strong>Product returns</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Return</th><th>Date</th><th>Items</th><th>Reason</th><th>By</th><th class="text-end">Refund</th></tr></thead><tbody>@foreach($order->returns as $return)<tr><td class="fw-semibold">{{ $return->return_number }}</td><td>{{ $return->returned_at->format('d M Y H:i') }}</td><td>@foreach($return->items as $returnItem)<div>{{ $returnItem->orderItem->product_name }} × {{ $returnItem->quantity }} <span class="small text-secondary">{{ $returnItem->restock ? 'restocked' : 'not restocked' }}</span></div>@endforeach</td><td>{{ $return->reason ?: '—' }}</td><td>{{ $return->creator?->name ?: 'System' }}</td><td class="text-end">{{ $order->currency->value }} {{ number_format((float) $return->refunds->sum('amount'), 2) }}</td></tr>@endforeach</tbody></table></div></div>@endif @endcan

        <div class="card"><div class="card-header bg-white"><strong>Activity timeline</strong></div><div class="list-group list-group-flush">@forelse($order->activities as $activity)<div class="list-group-item"><div class="d-flex justify-content-between gap-3"><span>{{ $activity->description }}</span><small class="text-secondary text-nowrap">{{ $activity->created_at->format('d M Y H:i') }}</small></div><small class="text-secondary">{{ $activity->creator?->name ?: 'System' }}</small></div>@empty<div class="list-group-item text-secondary">No recorded activity.</div>@endforelse</div></div>
    </div>

    <div class="col-xl-4">
        <div class="card mb-4"><div class="card-body"><h2 class="h5">Customer snapshot</h2><a class="fw-semibold" href="{{ route('customers.show', $order->customer) }}">{{ $order->customer_name ?: $order->customer->name }}</a><div>{{ $order->customer_phone ?: 'No phone provided' }}</div>@if($order->shipping_address)<div class="small text-secondary mt-1">{{ $order->shipping_address }}</div>@endif<hr><dl class="row mb-0"><dt class="col-5">Source</dt><dd class="col-7">{{ $order->source->label() }}</dd><dt class="col-5">Paid</dt><dd class="col-7">{{ $order->currency->value }} {{ number_format($paidTotal, 2) }}</dd><dt class="col-5">Refunded</dt><dd class="col-7">{{ $order->currency->value }} {{ number_format($refundedTotal, 2) }}</dd><dt class="col-5">Net paid</dt><dd class="col-7 fw-semibold">{{ $order->currency->value }} {{ number_format($netPaid, 2) }}</dd><dt class="col-5">Balance</dt><dd class="col-7">{{ $order->currency->value }} {{ number_format($balance, 2) }}</dd></dl>@if($order->notes)<hr><p class="mb-0">{{ $order->notes }}</p>@endif</div></div>

        @can('payments.create') @if($balance > 0)<div class="card mb-4"><div class="card-body"><h2 class="h5">Record payment</h2><form method="POST" action="{{ route('orders.payments.store', $order) }}">@csrf<input type="hidden" name="currency" value="{{ $order->currency->value }}"><div class="mb-3"><label class="form-label">Amount *</label><div class="input-group"><span class="input-group-text">{{ $order->currency->value }}</span><input class="form-control" type="number" step="0.01" min="0.01" max="{{ number_format($balance, 2, '.', '') }}" name="amount" required></div></div><div class="mb-3"><label class="form-label">Method *</label><select class="form-select" name="payment_method" required>@foreach($paymentMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Reference</label><input class="form-control" name="reference"></div><div class="mb-3"><label class="form-label">Paid at</label><input class="form-control" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}"></div><button class="btn btn-primary w-100">Record payment</button></form></div></div>@endif @endcan

        @can('payments.refund') @if($refundablePayments->isNotEmpty())<div class="card mb-4"><div class="card-body"><h2 class="h5">Standalone refund</h2><form method="POST" action="{{ route('orders.refunds.store', $order) }}">@csrf<div class="mb-3"><label class="form-label">Payment *</label><select class="form-select" name="payment_id" required>@foreach($refundablePayments as $entry)<option value="{{ $entry['payment']->id }}">{{ $entry['payment']->paid_at->format('d M') }} · {{ $entry['payment']->payment_method->label() }} · {{ $order->currency->value }} {{ number_format($entry['remaining'], 2) }} available</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Amount *</label><input class="form-control" type="number" step="0.01" min="0.01" name="amount" required></div><div class="mb-3"><label class="form-label">Refund method *</label><select class="form-select" name="refund_method" required>@foreach($paymentMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Reference</label><input class="form-control" name="reference"></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><button class="btn btn-outline-danger w-100">Record refund</button></form></div></div>@endif @endcan

        @can('returns.create') @if($order->status->value === 'completed' && $returnableItems->isNotEmpty())<div class="card"><div class="card-body"><h2 class="h5">Record product return</h2><form method="POST" action="{{ route('orders.returns.store', $order) }}">@csrf
            @foreach($returnableItems as $index => $entry)<div class="border rounded p-2 mb-2"><input type="hidden" name="items[{{ $index }}][order_item_id]" value="{{ $entry['item']->id }}"><div class="fw-semibold">{{ $entry['item']->product_name }} {{ $entry['item']->variant_name }}</div><div class="small text-secondary mb-2">{{ $entry['remaining'] }} returnable</div><div class="row g-2"><div class="col-5"><label class="form-label small">Quantity</label><input class="form-control form-control-sm" type="number" min="0" max="{{ $entry['remaining'] }}" value="0" name="items[{{ $index }}][quantity]"></div><div class="col-7 d-flex align-items-end"><input type="hidden" name="items[{{ $index }}][restock]" value="0"><div class="form-check mb-1"><input class="form-check-input" id="restock-{{ $entry['item']->id }}" type="checkbox" name="items[{{ $index }}][restock]" value="1" checked><label class="form-check-label" for="restock-{{ $entry['item']->id }}">Restock sellable item</label></div></div></div></div>@endforeach
            <div class="mb-3"><label class="form-label">Return reason</label><input class="form-control" name="reason"></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div>
            @can('payments.refund') @if($refundablePayments->isNotEmpty())<hr><div class="small text-secondary mb-2">Optional refund with this return</div><div class="mb-3"><label class="form-label">Payment</label><select class="form-select" name="payment_id"><option value="">No refund</option>@foreach($refundablePayments as $entry)<option value="{{ $entry['payment']->id }}">{{ $entry['payment']->payment_method->label() }} · {{ $order->currency->value }} {{ number_format($entry['remaining'], 2) }} available</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Refund amount</label><input class="form-control" type="number" step="0.01" min="0.01" name="refund_amount"></div><div class="mb-3"><label class="form-label">Refund method</label><select class="form-select" name="refund_method"><option value="">Choose</option>@foreach($paymentMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Refund reference</label><input class="form-control" name="refund_reference"></div>@endif @endcan
            <button class="btn btn-primary w-100">Record return</button>
        </form></div></div>@endif @endcan
    </div>
</div>
@endsection

