@extends('layouts.app')
@section('title', $order->order_number.' · SellAssist KH')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a href="{{ route('orders.index') }}">← Orders</a><h1 class="h3 mt-2 mb-1">{{ $order->order_number }}</h1><div class="text-secondary">Created {{ $order->created_at->format('d M Y, H:i') }} by {{ $order->creator?->name ?: 'System' }}</div></div><div class="d-flex gap-2"><span class="badge text-bg-secondary fs-6">{{ $order->status->label() }}</span><span class="badge text-bg-info fs-6">{{ $order->payment_status->label() }}</span></div></div>

@if($nextStatuses !== [])<div class="card mb-4"><div class="card-body d-flex flex-wrap align-items-center gap-2"><strong class="me-2">Next action</strong>@foreach($nextStatuses as $status)@php($permission = $status->value === 'cancelled' ? 'orders.cancel' : 'orders.update') @can($permission)<form method="POST" action="{{ route('orders.status.update', $order) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status->value }}"><button class="btn btn-sm {{ $status->value === 'cancelled' ? 'btn-outline-danger' : 'btn-primary' }}">{{ $status->label() }}</button></form>@endcan @endforeach</div></div>@endif

<div class="row g-4">
    <div class="col-xl-8">
        <div class="card mb-4"><div class="card-header bg-white"><strong>Items</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Product snapshot</th><th>SKU</th><th class="text-end">Price</th><th class="text-end">Qty</th><th class="text-end">Discount</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name }}<div class="small text-secondary">{{ $item->variant_name }}</div></td><td>{{ $item->sku ?: '—' }}</td><td class="text-end">{{ number_format((float) $item->unit_price, 2) }}</td><td class="text-end">{{ $item->quantity }}</td><td class="text-end">{{ number_format((float) $item->discount, 2) }}</td><td class="text-end fw-semibold">{{ number_format((float) $item->line_total, 2) }}</td></tr>@endforeach</tbody></table></div>
            <div class="card-body border-top"><div class="row justify-content-end"><div class="col-sm-6 col-lg-5"><div class="d-flex justify-content-between"><span>Subtotal</span><span>{{ $order->currency->value }} {{ number_format((float) $order->subtotal, 2) }}</span></div><div class="d-flex justify-content-between"><span>Discount</span><span>− {{ number_format((float) $order->discount, 2) }}</span></div><div class="d-flex justify-content-between"><span>Delivery</span><span>+ {{ number_format((float) $order->delivery_fee, 2) }}</span></div><div class="d-flex justify-content-between border-top mt-2 pt-2 fs-5 fw-bold"><span>Total</span><span>{{ $order->currency->value }} {{ number_format((float) $order->total, 2) }}</span></div></div></div></div>
        </div>
        @can('payments.view')<div class="card"><div class="card-header bg-white"><strong>Payments</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th>Recorded by</th><th class="text-end">Amount</th></tr></thead><tbody>@forelse($order->payments as $payment)<tr><td>{{ $payment->paid_at->format('d M Y H:i') }}</td><td>{{ $payment->payment_method->label() }}</td><td>{{ $payment->reference ?: '—' }}</td><td>{{ $payment->creator?->name ?: 'System' }}</td><td class="text-end">{{ $payment->currency->value }} {{ number_format((float) $payment->amount, 2) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">No payments recorded.</td></tr>@endforelse</tbody></table></div></div>@endcan
    </div>
    <div class="col-xl-4">
        <div class="card mb-4"><div class="card-body"><h2 class="h5">Customer</h2><a class="fw-semibold" href="{{ route('customers.show', $order->customer) }}">{{ $order->customer->name }}</a><div>{{ $order->customer->phone ?: 'No phone provided' }}</div><hr><dl class="row mb-0"><dt class="col-5">Source</dt><dd class="col-7">{{ $order->source->label() }}</dd><dt class="col-5">Paid</dt><dd class="col-7">{{ $order->currency->value }} {{ number_format($paidTotal, 2) }}</dd><dt class="col-5">Balance</dt><dd class="col-7 fw-semibold">{{ $order->currency->value }} {{ number_format($balance, 2) }}</dd></dl>@if($order->notes)<hr><p class="mb-0">{{ $order->notes }}</p>@endif</div></div>
        @can('payments.create')@if($balance > 0)<div class="card"><div class="card-body"><h2 class="h5">Record payment</h2><form method="POST" action="{{ route('orders.payments.store', $order) }}">@csrf<input type="hidden" name="currency" value="{{ $order->currency->value }}"><div class="mb-3"><label class="form-label">Amount *</label><div class="input-group"><span class="input-group-text">{{ $order->currency->value }}</span><input class="form-control" type="number" step="0.01" min="0.01" max="{{ number_format($balance, 2, '.', '') }}" name="amount" required></div></div><div class="mb-3"><label class="form-label">Method *</label><select class="form-select" name="payment_method" required>@foreach($paymentMethods as $method)<option value="{{ $method->value }}">{{ $method->label() }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Reference</label><input class="form-control" name="reference"></div><div class="mb-3"><label class="form-label">Paid at</label><input class="form-control" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}"></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div><button class="btn btn-primary w-100">Record payment</button></form></div></div>@endif @endcan
    </div>
</div>
@endsection

